import React, { useEffect, useState } from 'react';
import { NavLink, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import Layout from '../../components/Layout/Layout';
import Modal from '../../components/Modal/Modal';
import { PeriodControl } from '../Dashboard/DashboardControls';
import service from '../../services/branchPortalService';
import { currentPeriod, errorText, filterInvoices, invoiceNumber, invoiceStatuses, lessonTitle, localDate, localTime, money, periodName, validPeriod } from '../Invoices/invoiceData';
import { EmptyState, InvoiceList, InvoiceStatus, LoadingState, Notice, PortalIcon, StatCard } from '../Invoices/InvoiceUI';
import InvoiceDetail from '../Invoices/InvoiceDetail';
import '../Dashboard/OwnerDashboard.css';
import '../Calendar/Calendar.css';
import '../Invoices/Invoices.css';
import './BranchPortal.css';

const sections = [{ id: 'overview', label: 'Обзор', icon: 'overview' }, { id: 'lessons', label: 'Занятия', icon: 'cube' }, { id: 'invoices', label: 'Счета', icon: 'invoice' }, { id: 'analytics', label: 'Аналитика', icon: 'chart' }];
const plannedStatuses = { scheduled: 'По расписанию', confirmed: 'Подтверждено', needs_replacement: 'Подбираем преподавателя', cancelled: 'Отменено' };

function PriceDialog({ month, price, onClose, onSaved }) {
  const [value, setValue] = useState(price ?? ''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const save = async e => {
    e.preventDefault(); if (busy) return;
    const amount = String(value).trim() === '' ? null : Number(value);
    if (amount !== null && (!Number.isFinite(amount) || amount < 0)) { setError('Введите цену от 0 ₽ или оставьте поле пустым.'); return; }
    setBusy(true); setError('');
    try { await service.pricing(month, { retail_price_per_child: amount }); onSaved(); }
    catch (e) { setError(errorText(e)); } finally { setBusy(false); }
  };
  return <Modal isOpen title="Цена для родителей" onClose={() => { if (!busy) onClose(); }} size="small"><form className="bp-price-form" onSubmit={save}><div className="bp-price-context"><PortalIcon name="calendar" /><span>{periodName(month)}</span></div><p>Укажите, сколько сад получает за одно платное посещение. Рассчитаем вашу выручку и прибыль за выбранный месяц.</p>{error && <Notice tone="error">{error}</Notice>}<label className="iv-field">Цена за ребёнка за занятие, ₽<input type="number" inputMode="decimal" min="0" step="0.01" value={value} onChange={e => setValue(e.target.value)} placeholder="Например, 1 200" /></label><div className="bp-formula"><PortalIcon name="info" /><span>Прибыль = платные посещения × ваша цена − стоимость занятий клуба. Прочие расходы сада не учитываются.</span></div><p className="iv-muted">Цена применяется только к выбранному месяцу. Пустое поле отключает расчёт прибыли.</p><div className="iv-form-actions"><button type="button" className="od-control" onClick={onClose} disabled={busy}>Отмена</button><button type="submit" className="od-primary-btn" disabled={busy}>{busy ? 'Сохраняем…' : 'Сохранить цену'}</button></div></form></Modal>;
}

function LessonRows({ lessons, onOpen, planned = false, compact = false }) {
  return <div className={`bp-lesson-list ${compact ? 'bp-lessons-compact' : ''}`}>{lessons.map((lesson, index) => <button type="button" className={`bp-lesson-row ${planned ? 'bp-lesson-planned' : ''}`} key={`${lesson.id}-${index}`} onClick={() => onOpen({ ...lesson, planned })} aria-label={`${planned ? 'Запланировано' : 'Занятие'} ${localDate(lesson.starts_at)} ${localTime(lesson.starts_at)}, ${lessonTitle(lesson)}`}>
    <span className="bp-date-chip"><strong>{localDate(lesson.starts_at, { day: 'numeric', month: undefined })}</strong><small>{localDate(lesson.starts_at, { day: undefined, month: 'short' }).replace('.', '')}</small></span><span className="bp-lesson-title"><strong>{lessonTitle(lesson)}</strong><small><PortalIcon name="clock" />{localTime(lesson.starts_at)}<span>·</span>{lesson.teacher_name || 'Преподаватель уточняется'}</small></span>
    <span className="bp-lesson-attendance">{planned ? <span className={`iv-status iv-status-${lesson.status === 'cancelled' ? 'muted' : 'info'}`}>{plannedStatuses[lesson.status] || 'Запланировано'}</span> : <><strong>{Number(lesson.total_children ?? Number(lesson.paid_children || 0) + Number(lesson.trial_children || 0))}</strong><small>{Number(lesson.paid_children || 0)} платных · {Number(lesson.trial_children || 0)} пробных</small></>}</span>
    {!planned && <strong className="bp-lesson-amount">{money(lesson.amount)}</strong>}<PortalIcon name="right" />
  </button>)}</div>;
}

function LessonDialog({ lesson, onClose }) {
  const planned = lesson.planned;
  return <Modal isOpen onClose={onClose} title={planned ? 'Запланированное занятие' : 'Детали занятия'} size="medium"><div className="bp-lesson-detail"><span className="bp-detail-cube"><PortalIcon name="cube" /></span><h3>{lessonTitle(lesson)}</h3><p>{localDate(lesson.starts_at, { year: 'numeric' })} · {localTime(lesson.starts_at)}{lesson.duration_minutes ? ` · ${lesson.duration_minutes} мин` : ''}</p><div className="bp-teacher"><span className="bp-teacher-avatar">{(lesson.teacher_name || '?').split(' ').slice(0, 2).map(s => s[0]).join('')}</span><div><small>Преподаватель</small><strong>{lesson.teacher_name || 'Уточняется'}</strong></div></div>{planned ? <Notice tone="info">{plannedStatuses[lesson.status] || 'Запланировано'}. После проведения здесь появятся фактическая посещаемость и сумма.</Notice> : <><div className="bp-detail-counts"><div><span>Платных посещений</span><strong>{Number(lesson.paid_children || 0)}</strong></div><div><span>Пробных посещений</span><strong>{Number(lesson.trial_children || 0)}</strong></div></div><dl className="bp-calculation"><div><dt>Стоимость за платное посещение</dt><dd>{money(lesson.price_snapshot)}</dd></div><div><dt>Стоимость занятия</dt><dd>{money(lesson.amount)}</dd></div>{lesson.estimated_revenue !== null && lesson.estimated_revenue !== undefined && <><div><dt>Ваша расчётная выручка</dt><dd>{money(lesson.estimated_revenue)}</dd></div><div className="bp-profit-line"><dt>Ваша расчётная прибыль</dt><dd className={Number(lesson.estimated_profit) < 0 ? 'iv-negative' : ''}>{money(lesson.estimated_profit)}</dd></div></>}</dl><p className="iv-muted">Количество — посещения за это занятие. Пробные посещения не включены в расчёт стоимости.</p></>}</div></Modal>;
}

function AttendanceChart({ daily, financial = false, price }) {
  const values = daily.map(day => ({ ...day, label: localDate(day.date, { day: 'numeric', month: 'short' }), revenue: Number(day.paid_children) * Number(price || 0), profit: Number(day.paid_children) * Number(price || 0) - Number(day.amount) }));
  if (!values.length) return <EmptyState icon="chart" title="График появится после первого занятия">Здесь будет динамика по дням выбранного месяца.</EmptyState>;
  return <><div className="bp-chart-legend">{(financial ? [['Ваша выручка', 'var(--color-primary)'], ['Стоимость клуба', 'var(--color-secondary)']] : [['Платные посещения', 'var(--color-primary)'], ['Пробные посещения', 'var(--color-secondary)']]).map(([name, color]) => <span key={name}><i style={{ background: color }} />{name}</span>)}</div><div className="bp-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={values} barGap={3} margin={{ top: 10, right: 18, bottom: 0, left: 0 }} accessibilityLayer><CartesianGrid stroke="var(--color-border)" vertical={false} strokeDasharray="3 3" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: 'var(--color-text-muted)', fontSize: 11 }} minTickGap={20} /><YAxis axisLine={false} tickLine={false} allowDecimals={false} width={financial ? 55 : 32} tick={{ fill: 'var(--color-text-muted)', fontSize: 11 }} tickFormatter={v => financial && v >= 1000 ? `${v / 1000}к` : v} /><Tooltip cursor={{ fill: 'var(--color-bg-hover)' }} content={({ active, payload, label }) => active && payload?.length ? <div className="bp-chart-tooltip"><strong>{label}</strong>{payload.map(item => <div key={item.dataKey}><span><i style={{ background: item.color }} />{item.name}</span><b>{financial ? money(item.value) : item.value}</b></div>)}</div> : null} /><Bar name={financial ? 'Ваша выручка' : 'Платные посещения'} dataKey={financial ? 'revenue' : 'paid_children'} fill="var(--color-primary)" radius={[4, 4, 0, 0]} maxBarSize={32} /><Bar name={financial ? 'Стоимость клуба' : 'Пробные посещения'} dataKey={financial ? 'amount' : 'trial_children'} fill="var(--color-secondary)" radius={[4, 4, 0, 0]} maxBarSize={32} /></BarChart></ResponsiveContainer></div></>;
}

const exportLessons = (lessons, month) => {
  const cell = value => { let text = String(value ?? ''); if (/^[=+@-]/.test(text)) text = `'${text}`; return `"${text.replace(/"/g, '""')}"`; };
  const rows = [['Дата', 'Время', 'Занятие', 'Преподаватель', 'Платные посещения', 'Пробные посещения', 'Цена клуба', 'Стоимость'], ...lessons.map(l => [localDate(l.starts_at, { year: 'numeric' }), localTime(l.starts_at), lessonTitle(l), l.teacher_name, l.paid_children, l.trial_children, l.price_snapshot, l.amount])];
  const url = URL.createObjectURL(new Blob(['\uFEFF', rows.map(row => row.map(cell).join(';')).join('\r\n')], { type: 'text/csv;charset=utf-8' }));
  const a = document.createElement('a'); a.href = url; a.download = `Занятия-${month}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
};

export default function BranchPortal() {
  const { section: selectedSection } = useParams(), [params, setParams] = useSearchParams(), navigate = useNavigate();
  const section = sections.some(s => s.id === selectedSection) ? selectedSection : 'overview';
  const month = validPeriod(params.get('month')) ? params.get('month') : currentPeriod();
  const invoiceId = /^\d+$/.test(params.get('invoice') || '') ? params.get('invoice') : '';
  const [data, setData] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [refresh, setRefresh] = useState(0);
  const [invoices, setInvoices] = useState([]), [invoicesLoading, setInvoicesLoading] = useState(true), [invoicesError, setInvoicesError] = useState('');
  const [priceOpen, setPriceOpen] = useState(false), [lesson, setLesson] = useState(null), [notice, setNotice] = useState(''), [search, setSearch] = useState(''), [status, setStatus] = useState(''), [lessonView, setLessonView] = useState('completed'), [page, setPage] = useState(0);
  const updateParams = fields => { const next = new URLSearchParams(params); Object.entries(fields).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); setParams(next); };
  const go = nextSection => navigate(`/branch/${nextSection}?month=${month}`);
  useEffect(() => {
    const abort = new AbortController(); setLoading(true); setError('');
    service.overview(month, abort.signal).then(result => { if (!abort.signal.aborted) setData(result); }).catch(e => { if (!abort.signal.aborted) setError(errorText(e)); }).finally(() => { if (!abort.signal.aborted) setLoading(false); });
    return () => abort.abort();
  }, [month, refresh]);
  useEffect(() => {
    const abort = new AbortController(); setInvoicesLoading(true); setInvoicesError('');
    service.invoices(false, {}, abort.signal).then(result => { if (!abort.signal.aborted) setInvoices(result.items || []); }).catch(e => { if (!abort.signal.aborted) setInvoicesError(errorText(e)); }).finally(() => { if (!abort.signal.aborted) setInvoicesLoading(false); });
    return () => abort.abort();
  }, [refresh]);
  useEffect(() => { setSearch(''); setPage(0); setStatus(''); }, [section, month]);
  useEffect(() => { setPage(0); }, [search, status, lessonView]);
  const summary = data?.summary || {}, lessons = data?.lessons || [], upcoming = data?.upcoming || [], daily = data?.daily || [];
  const price = data?.pricing?.retail_price_per_child, hasPrice = price !== null && price !== undefined;
  const monthInvoices = (data?.invoices || []).filter(i => i.status !== 'cancelled');
  const dueInvoice = monthInvoices.find(i => i.status === 'issued') || monthInvoices.find(i => i.status === 'payment_reported');
  const query = search.trim().toLocaleLowerCase('ru');
  const visibleLessons = (lessonView === 'completed' ? lessons : upcoming).filter(l => !query || [lessonTitle(l), l.teacher_name, localDate(l.starts_at)].join(' ').toLocaleLowerCase('ru').includes(query));
  const visibleInvoices = filterInvoices(invoices, { search, status, month: params.get('period') === 'all' ? '' : month });
  const safePage = Math.min(page, Math.max(0, Math.ceil(visibleLessons.length / 20) - 1));
  const priceCard = <div className={`bp-price-card ${hasPrice ? 'bp-price-configured' : ''}`}><span className="bp-price-card-icon"><PortalIcon name="spark" /></span><h3>{hasPrice ? 'Ваша экономика занятий' : 'Узнайте прибыль вашего сада'}</h3><p>{hasPrice ? `Цена для родителей: ${money(price)} за платное посещение.` : 'Укажите свою цену для родителей — и увидите выручку и прибыль по каждому занятию.'}</p>{hasPrice && <strong className={Number(summary.estimated_profit) < 0 ? 'iv-negative' : ''}>{money(summary.estimated_profit)}<small>расчётная прибыль за месяц</small></strong>}<button type="button" className={hasPrice ? 'od-control' : 'od-primary-btn'} onClick={() => setPriceOpen(true)}><PortalIcon name={hasPrice ? 'edit' : 'plus'} />{hasPrice ? 'Изменить цену' : 'Указать свою цену'}</button></div>;
  return <Layout headerTitle="Кабинет сада" className="layout-branch-portal"><div className="bp-page iv-page">
    <div className="bp-heading"><div className="bp-identity"><span className="bp-building-icon"><PortalIcon name="building" /></span><div><span className="iv-eyebrow">ПАРТНЁР АЙТИ КЛУБА</span><h1>{data?.branch?.name || 'Ваш детский сад'}</h1><p>{data?.branch?.address || 'Занятия, расчёты и развитие вашего сада'}</p></div></div><div className="bp-heading-actions"><PeriodControl value={{ start: month, end: month }} onChange={p => updateParams({ month: p.start, period: '' })} allowRange={false} /><button type="button" className="od-icon-btn" aria-label="Обновить кабинет" disabled={loading} onClick={() => setRefresh(n => n + 1)}><PortalIcon name="repeat" /></button></div></div>
    <nav className="bp-nav" aria-label="Разделы кабинета сада">{sections.map(item => <NavLink key={item.id} to={`/branch/${item.id}?month=${month}`}><PortalIcon name={item.icon} />{item.label}{item.id === 'invoices' && !invoicesLoading && invoices.some(i => i.status === 'issued') && <span className="bp-nav-dot" aria-label="Есть счета к оплате" />}</NavLink>)}</nav>
    {notice && <Notice onClose={() => setNotice('')}>{notice}</Notice>}
    {section !== 'invoices' && (loading ? <LoadingState /> : error ? <Notice tone="error">{error}<button type="button" className="od-control" onClick={() => setRefresh(n => n + 1)}>Повторить</button></Notice> : <div className="bp-section" key={`${section}-${month}`}>
      {section === 'overview' && <>
        <div className="bp-section-title"><div><h2>Как проходит месяц</h2><p>Фактические занятия и расчёты за {periodName(month).toLowerCase()}</p></div><span className="bp-data-caption"><i />По отчётам преподавателей</span></div>
        <div className="iv-stats"><StatCard label="Проведено занятий" value={summary.lessons_count || 0} caption="С отчётом преподавателя" icon="cube" /><StatCard label="Посещений" value={summary.total_children || 0} caption={`${summary.paid_children || 0} платных · ${summary.trial_children || 0} пробных`} icon="people" /><StatCard label="Начислено за месяц" value={money(summary.accrued_amount)} caption="По проведённым занятиям" icon="chart" /><StatCard label="К оплате по счетам" value={money(summary.outstanding_amount)} caption="Выставленные и ещё не оплаченные" icon="wallet" accent /></div>
        <div className="bp-overview-grid"><div className="bp-main-column"><section className="iv-panel"><div className="iv-section-heading bp-panel-heading"><div><h3>Последние занятия</h3><p>Что собирали, кто проводил и сколько детей участвовало</p></div><button type="button" className="od-text-btn" onClick={() => go('lessons')}>Все занятия<PortalIcon name="right" /></button></div>{lessons.length ? <LessonRows lessons={[...lessons].sort((a, b) => String(b.starts_at).localeCompare(String(a.starts_at))).slice(0, 4)} onOpen={setLesson} compact /> : <EmptyState icon="cube" title="Месяц только начинается">После занятия преподаватель добавит отчёт — и он появится здесь.</EmptyState>}</section><section className="iv-panel"><div className="iv-section-heading bp-panel-heading"><div><h3>Ближайшие занятия</h3><p>Расписание в выбранном месяце</p></div><PortalIcon name="calendar" /></div>{upcoming.length ? <LessonRows lessons={upcoming.slice(0, 3)} onOpen={setLesson} planned compact /> : <div className="bp-quiet-empty"><PortalIcon name="calendar" /><p>Ближайших занятий в этом месяце пока нет в расписании.</p></div>}</section></div><aside className="bp-side-column"><section className="bp-balance-card"><div className="iv-section-heading"><h3>Расчёты за месяц</h3><PortalIcon name="invoice" /></div>{dueInvoice ? <><InvoiceStatus invoice={dueInvoice} /><strong>{money(dueInvoice.total_amount)}</strong><p>{invoiceNumber(dueInvoice)}{dueInvoice.due_date ? ` · до ${localDate(dueInvoice.due_date)}` : ''}</p><button type="button" className="od-primary-btn" onClick={() => updateParams({ invoice: String(dueInvoice.id) })}>Открыть счёт<PortalIcon name="right" /></button></> : <><span className="bp-balance-check"><PortalIcon name={monthInvoices.length ? 'check' : 'clock'} /></span><h4>{monthInvoices.some(i => i.status === 'paid') ? 'Все счета оплачены' : 'Счёт ещё не выставлен'}</h4><p>{monthInvoices.some(i => i.status === 'paid') ? 'Спасибо! Подтверждённые оплаты сохранены в истории.' : 'Начисления видны сразу после занятия. Готовый счёт появится здесь после выставления администратором.'}</p></>}<footer><span>Оплачено за период</span><strong>{money(summary.paid_amount)}</strong></footer></section>{priceCard}</aside></div>
      </>}
      {section === 'lessons' && <><div className="bp-section-title"><div><h2>Все занятия вашего сада</h2><p>Подробный журнал за {periodName(month).toLowerCase()}</p></div><button type="button" className="od-control" onClick={() => exportLessons(lessons, month)} disabled={!lessons.length}><PortalIcon name="download" />Скачать отчёт</button></div><section className="iv-panel"><div className="iv-journal-toolbar"><div className="iv-status-tabs"><button type="button" aria-pressed={lessonView === 'completed'} onClick={() => setLessonView('completed')}>Проведено<span>{lessons.length}</span></button><button type="button" aria-pressed={lessonView === 'planned'} onClick={() => setLessonView('planned')}>В расписании<span>{upcoming.length}</span></button></div><label className="iv-search"><PortalIcon name="search" /><input aria-label="Поиск занятий" value={search} onChange={e => setSearch(e.target.value)} placeholder="Модель или преподаватель" /></label></div>{visibleLessons.length ? <><div className="bp-lesson-tablehead" aria-hidden="true"><span>Дата</span><span>Занятие / преподаватель</span><span>{lessonView === 'planned' ? 'Статус' : 'Посещения'}</span>{lessonView === 'completed' && <span>Стоимость клуба</span>}</div><LessonRows lessons={visibleLessons.slice(safePage * 20, safePage * 20 + 20)} onOpen={setLesson} planned={lessonView === 'planned'} /><footer className="iv-list-footer"><span>{safePage * 20 + 1}–{Math.min((safePage + 1) * 20, visibleLessons.length)} из {visibleLessons.length}</span><div><button type="button" className="od-icon-btn" aria-label="Предыдущая страница занятий" disabled={safePage === 0} onClick={() => setPage(safePage - 1)}><PortalIcon name="left" /></button><button type="button" className="od-icon-btn" aria-label="Следующая страница занятий" disabled={(safePage + 1) * 20 >= visibleLessons.length} onClick={() => setPage(safePage + 1)}><PortalIcon name="right" /></button></div></footer></> : <EmptyState icon="cube" title={query ? 'Ничего не найдено' : lessonView === 'planned' ? 'Нет запланированных занятий' : 'Проведённых занятий пока нет'}>{query ? 'Попробуйте другое название или имя преподавателя.' : 'Выберите другой месяц или вернитесь позже.'}</EmptyState>}</section><p className="iv-bottom-note"><PortalIcon name="info" />Показываем посещения, а не уникальных детей. Нажмите на занятие, чтобы увидеть детализацию.</p></>}
      {section === 'analytics' && <><div className="bp-section-title"><div><h2>Экономика и посещаемость</h2><p>Понятные показатели за {periodName(month).toLowerCase()}</p></div>{hasPrice && <button type="button" className="od-control" onClick={() => setPriceOpen(true)}><PortalIcon name="edit" />Ваша цена: {money(price)}</button>}</div>{hasPrice ? <><div className="iv-stats"><StatCard label="Ваша расчётная выручка" value={money(summary.estimated_revenue)} caption={`${summary.paid_children || 0} платных посещений × ${money(price)}`} icon="wallet" /><StatCard label="Стоимость занятий клуба" value={money(summary.accrued_amount)} caption="Начислено по отчётам преподавателей" icon="invoice" /><StatCard label="Ваша расчётная прибыль" value={money(summary.estimated_profit)} caption="Выручка за вычетом стоимости клуба" icon="chart" accent negative={Number(summary.estimated_profit) < 0} /><StatCard label="В среднем на занятии" value={summary.lessons_count ? (Number(summary.total_children) / Number(summary.lessons_count)).toLocaleString('ru-RU', { maximumFractionDigits: 1 }) : '—'} caption="Платные и пробные посещения" icon="people" /></div><section className="iv-panel"><div className="iv-section-heading bp-panel-heading"><div><h3>Выручка и стоимость по дням</h3><p>Как проведённые занятия складываются в итог месяца</p></div></div><AttendanceChart daily={daily} financial price={price} /></section><p className="iv-bottom-note"><PortalIcon name="info" />Это расчётная прибыль: прочие расходы сада не учтены. Сумма выставленного счёта может отличаться от начислений после корректировок.</p></> : <div className="bp-analytics-intro">{priceCard}<div className="bp-formula-card"><span className="iv-eyebrow">КАК МЫ СЧИТАЕМ</span><h3>Ваша цена.<br />Прозрачный результат.</h3><div><span>Платные посещения</span><b>×</b><span>Цена для родителей</span><b>−</b><span>Стоимость клуба</span></div><p>Цена сохраняется для выбранного месяца. Вы можете обновить её в любой момент.</p></div></div>}<section className="iv-panel bp-attendance-panel"><div className="iv-section-heading bp-panel-heading"><div><h3>Посещаемость по дням</h3><p>{summary.paid_children || 0} платных и {summary.trial_children || 0} пробных посещений за месяц</p></div><PortalIcon name="people" /></div><AttendanceChart daily={daily} /></section></>}
    </div>)}
    {section === 'invoices' && <div className="bp-section"><div className="bp-section-title"><div><h2>Счета и оплаты</h2><p>Все выставленные счета, документы и история расчётов</p></div><button type="button" className={`od-control ${params.get('period') === 'all' ? 'is-filtered' : ''}`} aria-pressed={params.get('period') === 'all'} onClick={() => updateParams({ period: params.get('period') === 'all' ? '' : 'all' })}>Все периоды</button></div>{invoicesLoading ? <LoadingState label="Загружаем ваши счета…" /> : invoicesError ? <Notice tone="error">{invoicesError}<button type="button" className="od-control" onClick={() => setRefresh(n => n + 1)}>Повторить</button></Notice> : <><section className="iv-panel"><div className="iv-journal-toolbar"><div className="iv-status-tabs"><button type="button" aria-pressed={!status} onClick={() => setStatus('')}>Все счета</button>{['issued', 'payment_reported', 'paid', 'cancelled'].map(key => <button type="button" key={key} aria-pressed={status === key} onClick={() => setStatus(key)}>{invoiceStatuses[key].label}</button>)}</div><label className="iv-search"><PortalIcon name="search" /><input aria-label="Поиск ваших счетов" value={search} onChange={e => setSearch(e.target.value)} placeholder="Номер или сумма" /></label></div>{visibleInvoices.length ? <InvoiceList items={visibleInvoices} onOpen={id => updateParams({ invoice: String(id) })} /> : <EmptyState title={search || status ? 'Счета не найдены' : 'Счета пока не выставлены'}>{search || status ? 'Измените фильтр или поисковый запрос.' : 'Когда администратор выставит счёт за занятия, он появится здесь. Начисления доступны в обзоре.'}</EmptyState>}</section><div className="bp-payment-help"><PortalIcon name="shield" /><div><strong>Оплатили счёт? Сообщите об этом</strong><p>Откройте счёт и нажмите «Я оплатил». После проверки поступления администратором статус сменится на «Оплачен».</p></div></div></>}</div>}
    {priceOpen && <PriceDialog month={month} price={price} onClose={() => setPriceOpen(false)} onSaved={() => { setPriceOpen(false); setRefresh(n => n + 1); setNotice('Цена для родителей сохранена. Расчёт за выбранный месяц обновлён.'); }} />}
    {lesson && <LessonDialog lesson={lesson} onClose={() => setLesson(null)} />}
    {invoiceId && <InvoiceDetail key={invoiceId} id={invoiceId} onClose={() => updateParams({ invoice: '' })} onChanged={() => { setRefresh(n => n + 1); setNotice('Информация об оплате отправлена администратору.'); }} />}
  </div></Layout>;
}
