import React, { useRef, useState } from 'react';
import Modal from '../../components/Modal/Modal';
import { Choice } from '../Calendar/CalendarFields';
import Icon from './AccountingIcons';
import { currentPeriod, errorText, periodName } from './accountingData';
export default function CreateSheetModal({ isOpen, onClose, onSuccess, departments = [], initialPeriod = currentPeriod(), initialDepartment = '' }) {
  const [year, setYear] = useState(initialPeriod.slice(0, 4)), [month, setMonth] = useState(initialPeriod.slice(5)), [department, setDepartment] = useState(initialDepartment);
  const [saving, setSaving] = useState(false), [error, setError] = useState(''); const busy = useRef(false);
  const close = () => { if (!busy.current) onClose(); };
  const submit = async e => { e.preventDefault(); if (busy.current) return; if (!department) { setError('Выберите отдел'); return; } busy.current = true; setSaving(true); setError(''); try { await onSuccess({ year: Number(year), month: Number(month), department_id: Number(department) }); } catch (err) { setError(errorText(err)); } finally { busy.current = false; setSaving(false); } };
  return <Modal isOpen={isOpen} title="Новый денежный лист" onClose={close} size="accounting-form"><form className="ac-form" onSubmit={submit}><div className="ac-form-context"><Icon name="sheet" /><span>Один лист — один отдел и один месяц</span></div><div className="ac-form-grid"><Choice label="Месяц" required value={month} onChange={setMonth} disabled={saving} options={Array.from({ length: 12 }, (_, i) => ({ value: String(i + 1).padStart(2, '0'), label: periodName(`2000-${String(i + 1).padStart(2, '0')}`).replace(' 2000', '') }))} /><label className="ac-field">Год<input required type="number" min="2000" max="2100" value={year} onChange={e => setYear(e.target.value)} disabled={saving} /></label></div><Choice label="Отдел" required value={department} onChange={setDepartment} disabled={saving} options={departments.map(d => ({ value: String(d.id), label: d.name }))} placeholder="Выберите отдел" />{!departments.length && <p className="ac-muted">Список отделов ещё не загружен. Закройте форму и обновите листы.</p>}{error && <div className="ac-error" role="alert">{error}</div>}<footer className="ac-form-footer"><button className="od-control" type="button" disabled={saving} onClick={close}>Отмена</button><button className="od-primary-btn" disabled={saving || !departments.length}>{saving ? 'Создаём…' : 'Создать лист'}</button></footer></form></Modal>;
}
