import React, { useRef, useState } from 'react';
import Modal from '../../components/Modal/Modal';
import { calcIncomeNet, calcReferralAmount } from '../../utils/incomeCalc';
import Icon from './AccountingIcons';
import { amountSign, errorText, money, operationTypes, salaryPeriod } from './accountingData';
export default function OperationDetailModal({ operation: op, onClose, onDelete }) {
  const [confirm, setConfirm] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState(''); const busy = useRef(false);
  const close = () => { if (!busy.current) onClose(); };
  const remove = async () => { if (busy.current) return; busy.current = true; setSaving(true); setError(''); try { await onDelete(op); } catch (e) { setError(errorText(e)); } finally { busy.current = false; setSaving(false); } };
  const fields = op.type === 'income' ? [['Филиал', op.branch_name], ['Получатель', op.owner_name], ['Налог', money(op.tax_amount)], ['Рефералка', `${money(calcReferralAmount(op))}${op.referral_percent ? ` · ${op.referral_percent}% ${op.referral_from_net ? 'после налога' : 'от суммы'}` : ''}`], ['После удержаний', money(calcIncomeNet(op))], ...(op.referral_comment ? [['Комментарий', op.referral_comment]] : [])] : op.type === 'salary' ? [['Преподаватель', op.teacher_name], ['Кто платит', op.owner_name], ['Период', salaryPeriod(op.period_type)]] : op.type === 'expense' ? [['Описание', op.name], ['Кто потратил', op.owner_name]] : [['От кого', op.from_owner_name], ['Кому', op.to_owner_name]];
  return <Modal isOpen title={operationTypes[op.type].single} onClose={close} size="accounting-detail"><div className="ac-detail"><div className={`ac-detail-amount ac-type-${op.type}`}><Icon name={operationTypes[op.type].icon} /><strong>{amountSign(op)}{money(op.amount)}</strong></div><dl>{fields.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || '—'}</dd></div>)}<div><dt>Дата записи</dt><dd>{op.created_at ? new Date(op.created_at).toLocaleString('ru-RU') : '—'}</dd></div></dl>{confirm && <div className="ac-delete-confirm"><strong>Удалить эту операцию?</strong><p>Запись исчезнет из листа, его итоги и остатки пересчитаются.</p></div>}{error && <div className="ac-error" role="alert">{error}</div>}<footer className="ac-form-footer">{confirm ? <><button className="od-control" disabled={saving} onClick={() => setConfirm(false)}>Оставить запись</button><button className="ac-danger-btn" disabled={saving} onClick={remove}>{saving ? 'Удаляем…' : 'Удалить операцию'}</button></> : <><button className="od-text-btn ac-negative" onClick={() => setConfirm(true)}><Icon name="trash" />Удалить</button><button className="od-control" onClick={close}>Закрыть</button></>}</footer></div></Modal>;
}
